### ISSUE TITLE
Improving the handling of release keystores

### ISSUE THREAD

**Issue by ghost** [tommywalkie/sample-godot-rust-app#14]
I'm by no means a DevOps expert, but I think there are some things to correct about this workflow:
1. Do not regenerate the keystore in the workflow. You won't get the same key back, even when using the same password. Use symmetric encryption (see `gpg --symmetric`) and check the encrypted keystore into VCS. Then supply the decryption password as secret and decrypt it in teh workflow. [Here is a more detailed guide from GitHub][1].
2. The `ANDROID_RELEASE_KEYSTORE` isn't private, it is just the location of the .keystore file.
3. Neither is `ANDROID_RELEASE_KEYSTORE_USER`, the alias can be public.

~4. The store password and the key password (passed by `-storepass`, `-keypass`) should be different. The first is the password to the general keystore, the second is the password to the key within specified by the alias (or in Godot's terminology, the keystore user). Google has great documentation [here][2].~

EDIT: I just noticed point 4. doesn't apply to Godot projects, they don't allow for different passwords.

[1]: https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#limits-for-secrets
[2]: https://developer.android.com/studio/publish/app-signing#generate-key

**Comment by tommywalkie** [comment]
@Filius-Patris Mostly agree with your points. I can see why `gpg` would be useful as a security layer for secrets, but why did you mean by the following statement ?
> Do not regenerate the keystore in the workflow. You won't get the same key back even if using the same password.

**Comment by ghost** [comment]
Have you ever generated your own GPG keypair? You'll get a randomly-generated fingerprint, which cannot be regenerated. It identifies the private key only you posses and when you can sign something with that fingerprint, you can prove your identity. This is done in app distribution too. The app store wants you to sign your app, so that they can be sure that the updates are from the same user.

I'll try to set up a simpler GitHub Action CI with release signing. I'll notify you, if it works.

**Comment by ghost** [comment]
I've got my (test-)project working!
See [this repo][1] for details.

[1]: https://github.com/Filius-Patris/godot-android-test

**Comment by tommywalkie** [comment]
@Filius-Patris Ahh it makes sense ! 
Sorry, I'm still a bit new to Android projects. Thanks for the explanation and for the workflow, I'll implement it in the weekend.

**Comment by tommywalkie** [comment]
It (finally) [worked](https://github.com/tommywalkie/sample-godot-rust-app/runs/617851066?check_suite_focus=true) ! Thanks @Filius-Patris for guiding me !!
Can clean the CI workflow and the repo and close the issue.

**Comment by ghost** [comment]
Cool! I was also trying on your repo, but didn't get it to work. Nice job!

Nice project btw, the one thing I hate about Godot is GDScript. I am far from fluent in rust, but it is definitely a way more powerful language than GDScript. Maybe I'll use this template in a future project :wink:.

**Comment by ghost** [comment]
And while you're about the clean the pipeline, the steps [installing treee][1], [Checking project structure for troubleshooting][2] and [Checking final build structure for troubleshooting][3] could probably also be removed.

[1]: https://github.com/tommywalkie/sample-godot-rust-app/blob/1cbf9f9fd01c83626098410866e0167806095501/.github/workflows/ci.yml#L319
[2]: https://github.com/tommywalkie/sample-godot-rust-app/blob/1cbf9f9fd01c83626098410866e0167806095501/.github/workflows/ci.yml#L332-L333
[3]: https://github.com/tommywalkie/sample-godot-rust-app/blob/1cbf9f9fd01c83626098410866e0167806095501/.github/workflows/ci.yml#L350-L351

**Comment by tommywalkie** [comment]
@Filius-Patris Thanks again for the help and the feedback, also I spotted that the `--output` option in `gpg` is in fact decrypting the `release.keystore.gpg` file and re-create the `release.keystore` so I'm guessing we don't need to commit `release.keystore` after all.
