### ISSUE TITLE
Building/Testing on MacOS

### ISSUE THREAD

**Issue by tommywalkie** [tommywalkie/sample-godot-rust-app#9]
Currently cannot build/test for MacOS cause of the lack of a device using this operating system. Might be possible to build and release via Github Actions if using a proper toolchain, but I need someone with an actual device to test the final product.

If you manage to build and run `sample_godot_rust_app` on MacOS, I will need the following details :
- Rust toolchain used ? (Use `rustup show` command)
- Dependencies needed ? Aside from LLVM.
- Godot MacOS export preset ? (Can be found in `export_presets.cfg`)
- Additional needed changes in any `Cargo.toml` file or somewhere else ?

**Comment by ghost** [comment]
Uhm... sorry if I miss the point of this answer, but I just went ahead, cloned this repo to my MacBook Air (13-inch, 2017) and did `cargo build`, pointed the `core.gdnlib` to the right binary and hit 'Play' and it worked.

```zsh
$ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/tobtobxx/.rustup

stable-x86_64-apple-darwin (default)
rustc 1.43.1 (8d69840ab 2020-05-04)
```

I might have a version of llvm from Xcode or something...:
```zsh
$ llvm-gcc --version
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I'll be glad to provide further needed informations. Also note, that this is an actively used environment, not a highly isolated as it can be found in runners.

**Comment by tommywalkie** [comment]
@Filius-Patris Thanks ! This is exactly what I needed ! I wanted to make sure the MacOS build/export process was as simple as I thought, from a Windows/Linux user perspective.

Just tried a possible successful build (https://github.com/tommywalkie/sample-godot-rust-app/commit/c1796d80b295951866cee3d3aec05b1a1dd7b888) via Github, the final game 18MB size might be quite different from what I expected (compared to the other ones which are >40MB, maybe this is just compressed), but at least the CI setup was straightforward.

**EDIT** : Added `.zip` extension to the final MacOS export in https://github.com/tommywalkie/sample-godot-rust-app/commit/60a20fb7b7a7a258bd19ed519b48365f6dd44fac, just in case.

**Comment by tommywalkie** [comment]
Found out after downloading [`sample_godot_rust_app.app`](https://github.com/tommywalkie/sample-godot-rust-app/suites/691870827/artifacts/6539821) artifact in https://github.com/tommywalkie/sample-godot-rust-app/commit/60a20fb7b7a7a258bd19ed519b48365f6dd44fac is indeed compressing a ~30MB MacOS app so this might be good news.

@Filius-Patris Is it possible to test the artifact so I can confirm the build was good and close the issue ?

**Comment by ghost** [comment]
Hmm... Unfortunately I can't confirm it to be working.
Downloading and opening just yields this nice but useless error:
![Screenshot 2020-05-18 at 13 00 00](https://user-images.githubusercontent.com/37048904/82205962-ad53ea00-9907-11ea-9e33-bfd1d9c1012d.png)
I'll investigate it further, but for now the CI doesn't seem to be too successful.

**Comment by ghost** [comment]
Hmm... minor advancements:
I `chmod +x`ed the raw binary in the .app, and it now at least starts, but the Rust code doesn't seem to be loaded.

The behavior I observe is just a window with no (grey) background and the "go to second scene" button. Pressing it changes to the second scene, but the button "To first scene" doesn't do anything afterwards.

**Comment by tommywalkie** [comment]
@Filius-Patris Interesting, this access rights related issue is also a known issue on Linux builds (https://github.com/tommywalkie/sample-godot-rust-app/issues/10). I definitely need to address this someday.

> The behavior I observe is just a window with no (grey) background and the "go to second scene" button. Pressing it changes to the second scene, but the button "To first scene" doesn't do anything afterwards.

Yep. Can confirm this was the same behavior on an Android app that doesn't load properly GDNative scripts. Need to check if I messed up library paths somewhere...

Ah, spotted the issue. Should be `libcore.dylib` and not `core.dylib`. Will fix this.

https://github.com/tommywalkie/sample-godot-rust-app/blob/60a20fb7b7a7a258bd19ed519b48365f6dd44fac/scenes/core.gdnlib#L4

**Comment by tommywalkie** [comment]
@Filius-Patris Tried a new export in https://github.com/tommywalkie/sample-godot-rust-app/commit/fadbe85646958616754fb17711e3c02e55be0ea4.
As far as I can tell, a new `Frameworks` directory appeared in [the MacOS app archive artifact](https://github.com/tommywalkie/sample-godot-rust-app/suites/692255148/artifacts/6547442), including `libcore.dylib`.
Guessing this is the way MacOS apps handle libraries. 
Should be fine now but still need confirmation.

**Comment by ghost** [comment]
Yup, can confirm that it works on my MacBook Air (13-inch, 2017) after `chmod +x`ing the raw binary.

**Comment by tommywalkie** [comment]
Nice !! Can merge to `master` and close the issue. Huge thanks for your help @Filius-Patris !
